### ISSUE TITLE
googletrans

### ISSUE THREAD

**Issue by rivanstudents** [dhenza1415/SELFBOT1#3]
Traceback (most recent call last):
  File "selfbotsk.py", line 15, in <module>
    from googletrans import Translator
  File "/usr/local/lib/python3.5/dist-packages/googletrans/__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 10, in <module>
    import httpcore
  File "/usr/local/lib/python3.5/dist-packages/httpcore/__init__.py", line 1, in <module>
    from ._async.base import AsyncByteStream, AsyncHTTPTransport
  File "/usr/local/lib/python3.5/dist-packages/httpcore/_async/base.py", line 9
    yield b""

**Comment by letterlover** [comment]
> Traceback (most recent call last):
> File "selfbotsk.py", line 15, in
> from googletrans import Translator
> File "/usr/local/lib/python3.5/dist-packages/googletrans/**init**.py", line 6, in
> from googletrans.client import Translator
> File "/usr/local/lib/python3.5/dist-packages/googletrans/client.py", line 10, in
> import httpcore
> File "/usr/local/lib/python3.5/dist-packages/httpcore/**init**.py", line 1, in
> from ._async.base import AsyncByteStream, AsyncHTTPTransport
> File "/usr/local/lib/python3.5/dist-packages/httpcore/_async/base.py", line 9
> yield b""
